spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Spring_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

flyway:
  enabled: true
  locations: classpath:db/migration
  baselineOnMigrate: true
  sqlMigrationSuffix: .sql
  placeholders:
    key: value
  encoding: utf-8
